version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      TZ: "America/Vancouver"
      SERVER_NAME: "Bacon's Server"
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      
    ports:
      - 19132:19132/udp
    volumes:
      - ./mcbs:/data
    stdin_open: true
    tty: true

volumes:
  minecraft-server: {}