version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      SERVER_NAME: "Harrison's Server"
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      LEVEL_TYPE: amplified
      LEVEL_NAME: "Harrison's World"

    ports:
      - 19132:19132/udp
    volumes:
      - minecraft-server:/data
    stdin_open: true
    tty: true

volumes:
  minecraft-server: {}