version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      SERVER_NAME: "Bacon's Server"
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_NAME: "Bacon's World"
      CHAT_RESTRICTION: Disabled
      ALLOW_CHEATS: "true"

    ports:
      - 19132:19132/udp
    volumes:
      - minecraft-server:/data
    stdin_open: true
    tty: true

volumes:
  minecraft-server: {}