execute as @a run execute at @s run fill ~-5 ~-1 ~-5 ~5 ~5 ~5 air replace light_block ["block_light_level"=12]
execute as @a run execute at @s run fill ~-5 ~-1 ~-5 ~5 ~5 ~5 air replace light_block ["block_light_level"=8]
execute as @a run execute at @s run fill ~-5 ~-1 ~-5 ~5 ~5 ~5 air replace light_block ["block_light_level"=4]

##For Items
execute as @e[name="Sea Lantern",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="lantern",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="glowstone",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="shroomlight",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="soul lantern",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="soul torch",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="lit pumpkin",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="soul campfire",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="campfire",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="beacon",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="redstone torch",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name=torch,type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Sea Pickle",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Enchantment Table",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Glowstone Dust",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="End Rod",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Nether Star",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Glow Berries",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Glow Lichen",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]
execute as @e[name="Lava Bucket",type=item] at @s if block ~~~ air run setblock ~ ~ ~ light_block ["block_light_level"=4]

##For players - LAND ----------------------------------------------------------------------------------------
execute as @a at @s if block ~~~ water run tag @s add water
execute as @a at @s if block ~~~ flowing_water run tag @s add water

execute as @a[tag=!water,hasitem=[{item=dl:miner_helmet,location=slot.armor.head}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]

execute as @a[tag=!water,hasitem=[{item=dl:torch,location=slot.weapon.offhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=dl:torch,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=dl:torch,location=slot.weapon.offhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=dl:torch,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]

execute as @a[tag=!water,hasitem=[{item=soul_torch,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=torch,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=lantern,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=glowstone,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=shroomlight,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=sea_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=soul_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=lit_pumpkin,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=soul_campfire,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=campfire,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=beacon,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=end_rod,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]

execute as @a[tag=!water,hasitem=[{item=ochre_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=pearlescent_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]
execute as @a[tag=!water,hasitem=[{item=verdant_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=12]

#WEAK
execute as @a[tag=!water,hasitem=[{item=conduit,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=redstone_torch,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=enchanting_table,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=sea_pickle,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=glowstone_dust,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=nether_star,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=glow_lichen,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=glow_berries,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]
execute as @a[tag=!water,hasitem=[{item=lava_bucket,location=slot.weapon.mainhand}]] run execute at @s if block ~~1~ air run setblock ~ ~1 ~ light_block ["block_light_level"=8]

##Dynamic in water ------------------------------------------------------------------------------------
execute as @a[tag=water,hasitem=[{item=dl:miner_helmet,location=slot.armor.head}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]

execute as @a[tag=water,hasitem=[{item=dl:torch,location=slot.weapon.offhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=dl:torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=dl:torch,location=slot.weapon.offhand}]] run execute at @s if block ^ ^1 ^1  air run setblock ^ ^1 ^1  light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=dl:torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1  air run setblock ^ ^1 ^1  light_block ["block_light_level"=12]

execute as @a[tag=water,hasitem=[{item=soul_torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=glowstone,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=shroomlight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=sea_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=soul_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=lit_pumpkin,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=soul_campfire,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=campfire,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=beacon,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=end_rod,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]

execute as @a[tag=water,hasitem=[{item=soul_torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=glowstone,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=shroomlight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=sea_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=soul_lantern,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=lit_pumpkin,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=soul_campfire,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=campfire,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=beacon,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=end_rod,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]

execute as @a[tag=water,hasitem=[{item=ochre_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=pearlescent_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=verdant_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=12]

execute as @a[tag=water,hasitem=[{item=ochre_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=pearlescent_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]
execute as @a[tag=water,hasitem=[{item=verdant_froglight,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=12]

#WEAK
execute as @a[tag=water,hasitem=[{item=conduit,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=redstone_torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=enchanting_table,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=sea_pickle,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glowstone_dust,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=nether_star,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glow_lichen,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glow_berries,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=lava_bucket,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^2 ^1 air run setblock ^ ^2 ^1 light_block ["block_light_level"=8]

execute as @a[tag=water,hasitem=[{item=conduit,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=redstone_torch,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=enchanting_table,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=sea_pickle,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glowstone_dust,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=nether_star,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glow_lichen,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=glow_berries,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]
execute as @a[tag=water,hasitem=[{item=lava_bucket,location=slot.weapon.mainhand}]] run execute at @s if block ^ ^1 ^1 air run setblock ^ ^1 ^1 light_block ["block_light_level"=8]

execute as @a[tag=water] run tag @s remove water